### ISSUE TITLE
Draft the outline for the Contact Tracing app Whitepaper for PR

### ISSUE THREAD

**Issue by pedrocruzio** [Code4PuertoRico/covid19-response#1]
Reference Links:

- https://bluetrace.io/
- https://covid19-static.cdn-apple.com/applications/covid19/current/static/contact-tracing/pdf/ContactTracing-BluetoothSpecificationv1.1.pdf
- https://github.com/aranja/rakning-c19-app

**Comment by froi** [comment]
@pedrocruzio I've added some new files and directory structure to this repo.

- `/docs`: This directory will serve as a home for any documentation or documents that will help our response efforts.
- `/white-papers`: This directory will serve as a home for any white paper that is produced for our response efforts.

Please let me know how else I can hep.

**Comment by froi** [comment]
@pedrocruzio se está trabajando esto? Si no se esta trabajando vamos a cerrarlo y hacemos uno nuevo o lo reabrimos cuando se quiera trabajar.
