### ISSUE TITLE
Document PR covid 19 dashboards

### ISSUE THREAD

**Issue by froi** [Code4PuertoRico/covid19-response#2]
There appears to be two separate PR Covid19 dashboards for PR

- [Dashboard1: https://bioseguridad.maps.arcgis.com/apps/opsdashboard/index.html#/d7308c1abb4747e584329adf1215125e](https://bioseguridad.maps.arcgis.com/apps/opsdashboard/index.html#/d7308c1abb4747e584329adf1215125e)
- [Dashboard2: https://bioseguridad.maps.arcgis.com/apps/opsdashboard/index.html#/3bfb64c9a91944bc8c41edd8ff27e6df](https://bioseguridad.maps.arcgis.com/apps/opsdashboard/index.html#/3bfb64c9a91944bc8c41edd8ff27e6df)

Up to now the differences seem to be visual and in data structure. The data seem to be the same.

We have no way in knowing if both are "official". The domains are both under the `bioseguridad` umbrella.

**Comment by froi** [comment]
The dashboards seem to have different data sources:

- [Dashboard1](https://bioseguridad.maps.arcgis.com/apps/opsdashboard/index.html#/d7308c1abb4747e584329adf1215125e)

    - Disponibilidad y Censo de Camas – Bioseguridad vía EMResource- Departamento de Salud
    - Datos epidemiológicos- Informe de Coronavirus- Oficina de Epidemiología-Departamento de Salud
    - Defunciones- Registro Demográfico- Departamento de Salud
    - Localización de Hospitales y CDTs- SARAFS- Departamento de Salud
    - Inventario de Camas Licenciadas – SARAFS- Departamento de Salud
    - Órdenes y Compra de Ventiladores – Oficina de Administración- Departamento de Salud
    - Localización de los Centros Diálisis – Renal Network Region 3

    ![image](https://user-images.githubusercontent.com/1918027/82153065-3ea55c80-9833-11ea-9ef9-ae74f8f80c84.png)

- [Dashboard2](https://bioseguridad.maps.arcgis.com/apps/opsdashboard/index.html#/3bfb64c9a91944bc8c41edd8ff27e6df)

    - Hospitales y CDT’s – SARAFS – Departamento de Salud; Centros de Diálisis – Renal Network Region 3

    ![image](https://user-images.githubusercontent.com/1918027/82152959-ac9d5400-9832-11ea-8efc-5f4b961b4f46.png)

**Comment by froi** [comment]
There might be a possibility that they are A/B testing. The data seem to be the same with some tweaks to the UI of the dashboards.

Sadly there is no way of knowing. The [official URL still gives a 404](https://statuscovid19.pr.gov/)

![image](https://user-images.githubusercontent.com/1918027/82153378-10c11780-9835-11ea-8686-d2ba9ad5ee4d.png)

Without this URL working we have no idea which we are supposed to keep looking at. If the health department has changed the domain for the dashboard we have no knowledge of the new one.

**Comment by sanchobarriga** [comment]
Each Dashboard link is coupled with a REST content link, identified by the Widget ID.

For example, for dashboard 2, the ID is: 3bfb64c9a91944bc8c41edd8ff27e6df, ripped from the end of the url.
It's REST content link would be: https://www.arcgis.com/sharing/rest/content/items/3bfb64c9a91944bc8c41edd8ff27e6df/data

In Python, this Rest link can easily be called using the Beautiful Soup and json modules as follows.

url = 'https://www.arcgis.com/sharing/rest/content/items/3bfb64c9a91944bc8c41edd8ff27e6df/data'
from urllib.request import Request, urlopen
from bs4 import BeautifulSoup
import json
req = Request(url, headers={'User-Agent': 'Mozilla/5.0'})
html = urlopen(req)
soup = BeautifulSoup(html)    
output = json.loads(soup.text)

My limited understanding of ARCGIS data structure led to my extraction pipeline being a very tailored one, snooping very slowly through what was made available. Eventually I identified the "widgets" key in the ouput json contained information of great interest. 

In the case of Dashboard 2, there is a MapWidget that contains most of the tables of interest. This is not the case of Dashboard 1, at least not as well as I could tell.

**Comment by froi** [comment]
Thanks @sanchobarriga (nice username BTW 😆 )

I got a couple of suggestions for you.

Since the endpoint returns JSON to begin with you might want to use the [Requests library](https://2.python-requests.org/en/master/). It'll give you a cleaner way to work with JSON payloads.

Example:

```python
import requests

url = 'https://services5.arcgis.com/klquQoHA0q9zjblu/arcgis/rest/services/Datos_Totales/FeatureServer/0/query?f=json&where=1%3D1&returnGeometry=false&spatialRel=esriSpatialRelIntersects&outFields=*&outSR=102100&resultOffset=0&resultRecordCount=50&cacheHint=true'
response = requests.get(url)
data = response.json() # Will return a Python dictionary from the JSON payload
```
